### ISSUE TITLE
Url Login Undefined

### ISSUE THREAD

**Issue by genuineswe** [kritika27/ecommerce-store-reactjs-stripe-oauth2#1]
Reproduce:
1. Click login
2. Url -> https://undefined/authorize?redirect_uri=https%3A%2F%2Fwizardly-panini-81c8e1.netlify.app&_reactName=onClick&_targetInst=null&type=click&nativeEvent=%5Bobject%20MouseEvent%5D&target=%5Bobject%20HTMLButtonElement%5D&currentTarget=%5Bobject%20HTMLButtonElement%5D&eventPhase=3&bubbles=true&cancelable=true&timeStamp=2384&defaultPrevented=false&isTrusted=true&view=%5Bobject%20Window%5D&detail=1&screenX=1584&screenY=168&clientX=1584&clientY=40&pageX=1584&pageY=40&ctrlKey=false&shiftKey=false&altKey=false&metaKey=false&getModifierState=function%20Un(e)%7Bvar%20t%3Dthis.nativeEvent%3Breturn%20t.getModifierState%3Ft.getModifierState(e)%3A!!(e%3DFn%5Be%5D)%26%26!!t%5Be%5D%7D&button=0&buttons=0&relatedTarget=null&movementX=0&movementY=0&isDefaultPrevented=function%20ln()%7Breturn!1%7D&isPropagationStopped=function%20ln()%7Breturn!1%7D&scope=openid%20profile%20email&response_type=code&response_mode=query&state=SGp%2BbkFKZHRYZGtsZk5SZGw2Mm9zeDktb3YxNmEyaVRTa0I3VnNSdjV3Vw%3D%3D&nonce=TX5hWDNxbFBmSkZSSnBPU0x0SnJ0ZnNSektKMU1xVlVCeGpVSWtEaXNHWQ%3D%3D&code_challenge=krz6mGtQlnTx32qzmRxeQh8q6zzq7cFqSLlBH1vMZzQ&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiYXV0aDAtcmVhY3QiLCJ2ZXJzaW9uIjoiMS4zLjAifQ%3D%3D

Expected: correct url

Happened: no undefined on url

**Comment by kritika27** [comment]
The correct working link was already updated long ago. Hence, I am closing this issue.
